import globals from "globals";
import pluginJs from "@eslint/js";
import tseslint from "typescript-eslint";

/** @type {import('eslint').Linter.Config[]} */
export default [
	{ files: ["**/*.{js,mjs,cjs,ts}"] },
	{
		languageOptions: {
			globals: {
				...globals.browser
			}
		}
	},
	{ ignores: ["node_modules/", "mochawesome-report/", "junit_report/"] },
	{
		rules: {
			"accessor-pairs": "error",
			"array-bracket-newline": "error",
			"array-bracket-spacing": "off",
			"array-callback-return": "error",
			"array-element-newline": "off",
			"arrow-body-style": ["error"],
			"arrow-parens": 2,
			"arrow-spacing": "off",
			"block-scoped-var": "error",
			"block-spacing": "error",
			"brace-style": ["error", "1tbs", { allowSingleLine: true }],
			"callback-return": "error",
			/* Cspell:disable-next-line */
			"camelcase": "off",
			"capitalized-comments": "error",
			"class-methods-use-this": "off",
			"comma-spacing": "off",
			"comma-style": ["error", "last"],
			"complexity": "error",
			"computed-property-spacing": ["error", "never"],
			"consistent-return": "off",
			"consistent-this": "error",
			"curly": "error",
			"default-param-last": "error",
			"dot-location": ["error", "property"],
			"dot-notation": [
				"error",
				{
					allowKeywords: true
				}
			],
			"eol-last": "off",
			"func-call-spacing": "off",
			"func-name-matching": "error",
			"func-names": "off",
			"func-style": "off",
			"function-call-argument-newline": "off",
			"function-paren-newline": "off",
			"generator-star-spacing": "error",
			"global-require": "error",
			"guard-for-in": "error",
			"handle-callback-err": "error",
			"id-blacklist": "error",
			"id-length": "off",
			"id-match": "error",
			/* Cspell:disable-next-line */
			"implicit-arrow-linebreak": "off",
			"init-declarations": "off",
			"jsx-quotes": "error",
			"key-spacing": "off",
			"keyword-spacing": "error",
			"line-comment-position": "off",
			/* Cspell:disable-next-line */
			"linebreak-style": ["error", "unix"],
			"lines-around-comment": "off",
			"lines-around-directive": "error",
			"lines-between-class-members": "off",
			"max-classes-per-file": "error",
			"max-depth": "error",
			"max-lines": ["error", 900],
			"max-lines-per-function": ["error", { max: 120, skipComments: true, skipBlankLines: true }],
			"max-nested-callbacks": "error",
			"max-params": ["error", 4],
			"max-statements": "off",
			"max-statements-per-line": "error",
			"multiline-comment-style": ["error", "separate-lines"],
			"multiline-ternary": "off",
			"new-cap": "error",
			"new-parens": "error",
			"newline-after-var": "off",
			"newline-before-return": "off",
			"newline-per-chained-call": "off",
			"no-alert": "error",
			"no-array-constructor": "error",
			"no-await-in-loop": "error",
			"no-bitwise": "error",
			"no-buffer-constructor": "error",
			"no-caller": "error",
			"no-catch-shadow": "error",
			"no-confusing-arrow": "error",
			"no-console": "off",
			"no-continue": "error",
			"no-div-regex": "error",
			"no-duplicate-imports": "error",
			"no-else-return": "error",
			"no-empty-function": "error",
			"no-eq-null": "error",
			"no-eval": "error",
			"no-extend-native": "error",
			"no-extra-bind": "error",
			"no-extra-label": "error",
			"no-extra-parens": "error",
			"no-floating-decimal": "error",
			"no-implicit-coercion": "error",
			"no-implicit-globals": "error",
			"no-implied-eval": "error",
			"no-inline-comments": "error",
			"no-invalid-this": "off",
			"no-iterator": "error",
			"no-label-var": "error",
			"no-labels": "error",
			"no-lone-blocks": "error",
			"no-lonely-if": "error",
			"no-loop-func": "error",
			"no-magic-numbers": "off",
			"no-mixed-operators": [
				"error",
				{
					allowSamePrecedence: true
				}
			],
			"no-mixed-requires": "error",
			"no-multi-assign": "error",
			"no-multi-str": "error",
			"no-multiple-empty-lines": "error",
			"no-native-reassign": "error",
			"no-negated-condition": "error",
			"no-negated-in-lhs": "error",
			"no-nested-ternary": "error",
			"no-new": "error",
			"no-new-func": "error",
			"no-new-object": "error",
			"no-new-require": "error",
			"no-new-wrappers": "error",
			"no-octal-escape": "error",
			"no-param-reassign": "off",
			"no-path-concat": "error",
			/* Cspell:disable-next-line */
			"no-plusplus": "off",
			"no-process-env": "error",
			"no-process-exit": "off",
			"no-proto": "error",
			"no-restricted-globals": "error",
			"no-restricted-imports": "error",
			"no-restricted-modules": "error",
			"no-restricted-properties": "error",
			"no-restricted-syntax": "error",
			"no-return-assign": "error",
			"no-return-await": "error",
			"no-script-url": "error",
			"no-self-compare": "error",
			"no-sequences": "error",
			"no-shadow": "error",
			"no-spaced-func": "off",
			"no-sync": "off",
			"no-tabs": [
				"error",
				{
					allowIndentationTabs: true
				}
			],
			"no-template-curly-in-string": "off",
			"no-throw-literal": "error",
			"no-trailing-spaces": "error",
			"no-undef-init": "error",
			"no-undefined": "off",
			"no-underscore-dangle": "off",
			"no-unmodified-loop-condition": "off",
			"no-unneeded-ternary": "error",
			"no-unused-expressions": "off",
			"no-use-before-define": "off",
			"no-useless-call": "error",
			"no-useless-computed-key": "error",
			"no-useless-concat": "off",
			"no-useless-constructor": "error",
			"no-useless-rename": "error",
			"no-useless-return": "error",
			"no-var": "error",
			"no-void": "error",
			"sort-imports": ["off", { ignoreMemberSort: false }],
			"no-warning-comments": "off",
			"no-whitespace-before-property": "error",
			/* Cspell:disable-next-line */
			"nonblock-statement-body-position": "error",
			"object-curly-newline": 0,
			"object-curly-spacing": "off",
			"object-shorthand": "error",
			"one-var": "off",
			"one-var-declaration-per-line": "error",
			"operator-assignment": "error",
			/* Cspell:disable-next-line */
			"operator-linebreak": "error",
			"padded-blocks": "off",
			"padding-line-between-statements": ["error"],
			"prefer-arrow-callback": "off",
			"prefer-const": "off",
			"prefer-destructuring": "off",
			"prefer-named-capture-group": "error",
			"prefer-numeric-literals": "error",
			"prefer-object-spread": "error",
			"prefer-promise-reject-errors": "error",
			"prefer-reflect": "error",
			"prefer-regex-literals": "error",
			"prefer-rest-params": "error",
			"prefer-spread": "error",
			"prefer-template": "off",
			"quote-props": "off",
			"quotes": "off",
			"radix": "error",
			"require-await": "error",
			"require-jsdoc": "off",
			"require-unicode-regexp": "off",
			"rest-spread-spacing": "error",
			"semi": "off",
			"semi-spacing": [
				"error",
				{
					after: true,
					before: false
				}
			],
			"semi-style": ["error", "last"],
			"sort-keys": "off",
			"sort-vars": "error",
			"space-before-blocks": "off",
			"space-before-function-paren": "off",
			"space-in-parens": ["error", "never"],
			"space-infix-ops": "off",
			"space-unary-ops": "error",
			"spaced-comment": ["error", "always"],
			"strict": "error",
			"switch-colon-spacing": "error",
			"symbol-description": "error",
			"template-curly-spacing": ["error", "never"],
			"template-tag-spacing": "error",
			"comma-dangle": "error",
			"max-len": ["error", 260],
			"no-multi-spaces": "error",
			"default-case": "error",
			"eqeqeq": ["error", "smart"],
			"indent": ["error", "tab"],
			"constructor-super": "error",
			"for-direction": "error",
			"getter-return": "error",
			"no-async-promise-executor": "error",
			"no-case-declarations": "error",
			"no-class-assign": "error",
			"no-compare-neg-zero": "error",
			"no-cond-assign": "error",
			"no-const-assign": "error",
			"no-constant-condition": "error",
			"no-control-regex": "error",
			"no-debugger": "error",
			"no-delete-var": "error",
			"no-dupe-args": "error",
			"no-dupe-class-members": "error",
			"no-dupe-else-if": "error",
			"no-dupe-keys": "error",
			"no-duplicate-case": "error",
			"no-empty": "error",
			"no-empty-character-class": "error",
			"no-empty-pattern": "error",
			"no-ex-assign": "error",
			"no-extra-boolean-cast": "off",
			"no-extra-semi": "error",
			"no-fallthrough": "error",
			"no-func-assign": "error",
			"no-global-assign": "error",
			"no-import-assign": "error",
			"no-inner-declarations": "error",
			"no-invalid-regexp": "error",
			"no-irregular-whitespace": "error",
			"no-loss-of-precision": "error",
			"no-misleading-character-class": "error",
			"no-mixed-spaces-and-tabs": "error",
			"no-new-symbol": "error",
			/* Cspell:disable-next-line */
			"no-nonoctal-decimal-escape": "error",
			"no-obj-calls": "error",
			"no-octal": "error",
			"no-prototype-builtins": "error",
			"no-redeclare": "error",
			"no-regex-spaces": "error",
			"no-self-assign": "error",
			"no-setter-return": "error",
			"no-shadow-restricted-names": "error",
			"no-sparse-arrays": "error",
			"no-this-before-super": "error",
			"no-undef": "error",
			"no-unexpected-multiline": "error",
			"no-unreachable": "error",
			"no-unsafe-finally": "error",
			"no-unsafe-negation": "error",
			"no-unsafe-optional-chaining": "error",
			"no-unused-labels": "error",
			"no-unused-vars": "error",
			"no-useless-backreference": "error",
			"no-useless-catch": "error",
			"no-useless-escape": "error",
			"no-with": "error",
			"require-yield": "error",
			"use-isnan": "error",
			"valid-typeof": "error",
			"@tseslint/no-require-imports": "off"
		}
	},
	pluginJs.configs.recommended,
	...tseslint.configs.recommended
];
